import type { NextPage } from "next"
import Head from "next/head"
import { useRouter } from "next/router"
import { FormEventHandler, useContext, useState } from "react"
import Button, { Variant } from "../components/Button"
import { UserContext } from "../context/UserContext"
import { trpc } from "../utils/trpc"

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }])
  const [userName, setUserName] = useState<string>()
  const { user, setUser } = useContext(UserContext)
  const createUser = trpc.useMutation("user.createUser")
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    if (!userName) return
    const myUser = await createUser.mutateAsync({
      name: userName,
    })
    setUser(myUser)
    router.push("/dashboard")
  }

  const handleSetUserName = (e: React.ChangeEvent<HTMLInputElement>) => {
    setUserName(e.target.value)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center  gap-4 justify-center min-h-screen p-4">
        <h1 className="text-4xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Online Chat Room
        </h1>
        <form className="flex flex-col gap-4" action="" onSubmit={handleSubmit}>
          <input
            onChange={handleSetUserName}
            type="text"
            placeholder="username"
            className="p-2 text-xl border"
          />
          <Button variant={Variant.Primary}>Sign In</Button>
        </form>
      </main>
    </>
  )
}

export default Home
